version: '3.8'
services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - DATABASE_TYPE=sqlite
      - DB_SQLITE_VACUUM_ON_STARTUP=true
      # Добавляем переменные для работы с локальными сервисами
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - ./n8n_persist:/home/node/.n8n
      - ./documents:/documents  # Папка для загружаемых документов
    depends_on:
      - qdrant
    networks:
      - rag-network

  # Qdrant векторная база данных
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"  # REST API
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      # Настройки Qdrant
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  qdrant_storage:
  n8n_persist:
  documents:
    